# Generated by Django 5.1.5 on 2025-01-27 08:46

import django.db.models.deletion
import mptt.fields
import products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[products.validators.validate_category_name])),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('top_level_category', models.CharField(blank=True, choices=[('shoes', 'Shoes'), ('clothing', 'Clothing'), ('accessories', 'Accessories'), ('electronics', 'Electronics'), ('home', 'Home'), ('toys', 'Toys'), ('beauty', 'Beauty'), ('food', 'Food'), ('books', 'Books'), ('sports', 'Sports'), ('outdoors', 'Outdoors'), ('automotive', 'Automotive'), ('music', 'Music'), ('games', 'Games'), ('art', 'Art'), ('collectibles', 'Collectibles'), ('other', 'Other')], help_text='Required only for top-level categories', max_length=20, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'active'), ('inactive', 'inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order'],
            },
        ),
    ]
