# Generated by Django 5.1.5 on 2025-02-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage_clothingproduct_shoeproduct_shoecolor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoecolor',
            name='image',
        ),
        migrations.AlterField(
            model_name='shoevariant',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shoevariant',
            name='size',
            field=models.CharField(max_length=10),
        ),
    ]
