# Generated by Django 5.1.5 on 2025-02-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_shoecolor_image_alter_shoevariant_color_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoecolor',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='shoesize',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='shoeproduct',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='shoe_products', to='products.shoecolor'),
        ),
        migrations.AddField(
            model_name='shoeproduct',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='shoe_products', to='products.shoesize'),
        ),
        migrations.RemoveField(
            model_name='shoecolor',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shoesize',
            name='product',
        ),
    ]
