# Generated by Django 5.1.5 on 2025-02-15 09:27

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_shoecolor_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoecolor',
            options={'ordering': [django.db.models.functions.text.Lower('color')]},
        ),
        migrations.AddField(
            model_name='clothingproduct',
            name='prod_type',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='shoeproduct',
            name='prod_type',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
