# Generated by Django 5.1.5 on 2025-02-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_shoecolor_options_clothingproduct_prod_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingproduct',
            name='creation_type',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('clothing', 'Clothing')], default='shoes', editable=False, max_length=15),
        ),
        migrations.AddField(
            model_name='shoeproduct',
            name='creation_type',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('clothing', 'Clothing')], default='shoes', editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='category',
            name='top_level_category',
            field=models.CharField(blank=True, choices=[('shoes', 'Shoes'), ('clothing', 'Clothing')], help_text='Required only for top-level categories', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clothingproduct',
            name='prod_type',
            field=models.CharField(blank=True, editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='shoeproduct',
            name='prod_type',
            field=models.CharField(blank=True, editable=False, max_length=15),
        ),
    ]
