# Generated by Django 5.1.5 on 2025-02-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_clothingproduct_creation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingproduct',
            name='creation_type',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('clothing', 'Clothing')], max_length=15),
        ),
        migrations.AlterField(
            model_name='shoeproduct',
            name='creation_type',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('clothing', 'Clothing')], max_length=15),
        ),
    ]
